#!/bin/bash

echo "$MAILNAME" > /etc/mailname
cp /etc/aliases.stub /etc/aliases
echo "root: $POSTMASTER" >> /etc/aliases

/usr/bin/newaliases

chown -R Debian-exim /var/spool/exim4
chown -R Debian-exim /var/mail
