name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1
      name: Login to GitHub Container Registry
      with:
        registry: ghcr.io
        username: c2c-bot-gis-ci
        password: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/camptocamp/exim:$(date +%Y%m%d)

    - name: Push the Docker image
      run: docker push ghcr.io/camptocamp/exim:$(date +%Y%m%d)
